services:
  grafana:
    image: grafana/grafana:11.5.2-ubuntu
    container_name: grafana
    restart: on-failure:5
    # labels:
    #   - traefik.enable=true
    #   - traefik.http.routers.grafana.ruel=Host(`grafana.test`)
    #   - traefik.http.services.grafana-service.loadbalancer.server.scheme=http
    #   - traefik.http.services.grafana-service.loadbalancer.server.port=3000
    ports:
      - 3000:3000

    networks:
      - graf-prom-network
    
networks:
  graf-prom-network:
    external: true
